language: python
python: "3.6"

before_install:
    - sudo apt-get install -y libxml2-utils

script:
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch
    - git diff --name-only --diff-filter=AM origin/${TRAVIS_BRANCH} HEAD | grep ".xml" | grep -v "Templates.xml" | xargs -d '\n' xmllint --noout
    - python fix_spells.py --dry-run --verbose
    - python create_compendiums.py
    - python create_compendiums.py --excludes
    - python create_compendiums.py --excludes --subtype-format usable
